name: CI/CD with i686-elf-gcc and i686-elf-g++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib qemu qemu-system-x86 nasm xorriso grub-common grub-pc-bin mtools make binutils-gold tcc 
        sudo apt-get install -y gcc-11-i686-linux-gnu g++-11-i686-linux-gnu || true
        sudo apt-get install -y gcc-i686-linux-gnu g++-i686-linux-gnu
        git clone https://github.com/lordmilko/i686-elf-tools
        unzip i686-elf-tools-linux.zip -d test
        cd test
        ./i686-elf-tools.sh linux



    - name: Try to fix broken packages
      run: sudo apt-get install -f

    - name: Set PATH for i686-elf-gcc and i686-elf-g++
      run: |
        export PATH="$PATH:/usr/bin:/usr/local/bin:/path/to/i686-elf-gcc-directory/bin:/path/to/i686-elf-g++-directory/bin" # Replace with the actual paths to i686-elf-gcc and i686-elf-g++ directories

    - name: Build project
      run: |
        # nasm -f elf32 -O0 kernelz/src/core/cpuhelper.asm -o kernelz/obj/core/cpuhelper.o
        make run # Replace 'make' with your build command
