name: Fudge Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget bzip2 xz-utils unzip help2man libtool-bin

      - name: Download crosstool-ng Source Code
        run: wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.26.0.tar.bz2

      - name: Extract crosstool-ng Source Code
        run: tar xjf crosstool-ng-1.26.0.tar.bz2

      - name: Configure and Install crosstool-ng
        run: |
          cd crosstool-ng-1.26.0
          ./configure
          make
          sudo make install

      - name: Copy Pre-generated .config File
        run: cp /path/to/your/pre-generated/config/.config crosstool-ng-1.26.0/.config

      - name: Build Cross-Compiler
        run: |
          cd crosstool-ng-1.26.0
          make

      - name: Clone Fudge Repository
        run: git clone git://github.com/jezze/fudge.git

      - name: Set PATH for Cross-Compiler
        run: export PATH=/home/$(whoami)/x-tools/i386-unknown-elf/bin:$PATH

      - name: Build Fudge
        run: |
          cd fudge
          make

      - name: Run Fudge in QEMU
        run: |
          ./vmctrl runsimple node1

      - name: Test Fudge
        run: |
          # Add testing commands here
