name: HiesenKernel

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the operating system you're using

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # This step checks out your repository

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget bzip2 xz-utils unzip help2man libtool-bin nasm python2 python3 python-pip grub-common xorriso mtools
          python2 -m pip install -r kernel/requirements.txt
          
      - name: Run Make Command
        run: |
          cd kernel
          make cdrom
