name: HiesenKernel

on:
  push:
    branches:
      - Caps  # Adjust branch name as needed
      - main

jobs:
  build:
    runs-on: macos-10.15  # Specify the operating system you're using

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # This step checks out your repository

      - name: Install Dependencies
        run: |
          # sudo apt-get update
          # sudo apt-get install -y build-essential git wget bzip2 xz-utils unzip help2man libtool-bin nasm python2 python3 python-pip grub-common xorriso mtools  build-essential build-essential gcc-multilib g++-multilib build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo  
          # python2 -m pip install -r kernel/requirements.txt
          # docker run -it -v "/home/admin:/root" --rm lordmilko/i686-elf-tools
          # docker run -it -v "/home/admin:/root" --rm lordmilko/i686-elf-tools -gv 9.2.0 -bv 2.34 -dv 9.1
          # sudo -s
          # wget https://raw.githubusercontent.com/lordmilko/i686-elf-tools/master/i686-elf-tools.sh
          # chmod +x ./i686-elf-tools.sh
          # ./i686-elf-tools.sh
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # brew install git wget bzip2 xz unzip nasm python@3 xorriso mtools gcc@11
          # python3 -m pip install -r kernel/requirements.txt
          # brew tap nativeos/i686-elf-toolchain
          brew services start selenium-server
          brew install i686-elf-binutils 
          # i686-elf-gcc i686-elf-newlib





          
      - name: Run Make Command
        run: |
          make
          cd kernel
          make
